pet_store/cart/urls.py
from django.urls import path
from .import views
urlpatterns =[
    path('add_to_cart/<int:id>',views.add_to_cart,name="add_to_cart"),
    path('cartpage',views.cart_name,name="cartpage"),
    path('cart_delete/<int:id>',views.delete_cart_product,name='cart_delete'),
    path('updatecart/<int:id>/',views.update_cart,name='updatecart'),
]

pet_store/orders/urls.py
from django.urls import path
from .import views

app_name="orders"
urlpatterns = [
    path('billing/',views.place_order,name='place_order'),
]

pet_store/pet_store/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings
from account.views import register,MyLoginView,MyLogoutView
#from django.contrib.auth import views as auth_view
from petsapp.views import pet_list

urlpatterns = [
    path('admin/', admin.site.urls),
    path('petsapp/',include('petsapp.urls'),name='pets'),
    path('cart/',include('cart.urls'),name='cart'),
    path('',pet_list,name='home'),
    path('register/',register,name='register-page'),
    path('login/',MyLoginView.as_view(template_name='base/login.html'),name='login'),
    path('logout/',MyLogoutView.as_view(),name='logout'),
    path('orders/',include('orders.urls'),name='orders'),
]

if settings:
    urlpatterns +=static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

pet_store/cart/models.py
from django.db import models
from petsapp.models import Pet
from django.contrib.auth.models import User

# Create your models here.

class Cart(models.Model):
    cart_id = models.CharField(max_length=300,blank=True)
    pet = models.ForeignKey(Pet,on_delete=models.CASCADE)
    user = models.ForeignKey(User,on_delete=models.CASCADE)
    quantity = models.IntegerField(default=1)
    totalprice = models.FloatField(default=0.00)
    timestamp = models.DateTimeField(auto_now_add=True)

    class Meta:
        db_table = 'cart'

pet_store/cart/forms.py
from .models import Orders,Payment,OrderPet,Pet
from django import forms


class OrderForm(forms.modelForm):
    status = (('new','new'),('pending','pending'),('delivered','devlivered'),('cancelled','cancelled'))

    states = [
        ('AP','Andhra Pradesh'),
        ('AR','Arunachal Pradesh'),
        ('AS','Assam'),
        ('BR','Bihar'),
        ('GOA','Goa'),
        ('GJ','Gajrat'),
        ('RJ','Rajasthan'),
        ('MH','Maharashtra'),
        ('UP','Uttar Pradesh'),
    ]   



    first_name= forms.CharField(max_length=100,widget=forms.TextInput(attrs={'class':'form-control'})) 
    last_name= forms.CharField(max_length=100,widget=forms.TextInput(attrs={'class':'form-control'})) 
    phone= forms.CharField(max_length=10,widget=forms.TextInput(attrs={'class':'form-control'})) 
    email= forms.CharField(max_length=50,widget=forms.TextInput(attrs={'class':'form-control'}))
    address= forms.CharField(max_length=200,widget=forms.TextInput(attrs={'class':'form-control'})) 
    country= forms.CharField(max_length=100,widget=forms.TextInput(attrs={'class':'form-control'}))
    state= forms.CharField(widget=forms.Select(choices=states,attrs={'class':'form-control'})) 
    city= forms.CharField(max_length=50,widget=forms.TextInput(attrs={'class':'form-control'}))  


    class Meta:
        models = Orders
        fields = ['first_name','last_name','phone','email','address','country','state','city'] 

pet_store/cart/views.py
from django.http import JsonResponse
from django.shortcuts import render,redirect
from petsapp.models import Pet
from .models import Cart
from django.contrib import messages
from django.db.models import Sum

# Create your views here.



def add_to_cart(request,id):
    cart_id = request.session.session_key
    if cart_id == None:
        cart_id = request.session.create()

    pet = Pet.objects.get(id=id)
    price = pet.price
    user = request.user

    Cart(cart_id=cart_id,pet=pet,user=user,totalprice=price).save()
    messages.success(request,"Item Added to Cart Successfully")
    return redirect('/')


def cart_name(request):
    all_items = Cart.objects.filter(user=request.user)
    flag = all_items.exists()
    return render(request,'cart/cart_home.html',{'items':all_items,'flag':flag})


def delete_cart_product(request,id):
    cart = Cart.objects.get(id=id)
    cart.delete()
    messages.success(request,"Item Removed From Cart Successfully")
    return redirect('cartpage')



def update_cart(request,id):
    p = request.POST.get('price')
    q = request.POST.get('qnt')
    p_id = request.POST.get('id')
    totalPrice = float(p) * int(q)
    Cart.objects.filter(id=p_id).update(quantity=q,totalprice=totalPrice)
   # total = Cart.objects.filter(user=request.user).aggregate(totalprice = Sum(F('totalprice') * F('quantity')))
    total_amount = Cart.objects.filter(user=request.user).aggregate(total=Sum ('totalprice'))['total'] or 0.0 
    return JsonResponse({'status':True,'totalprice':totalPrice,
    'total_amount':total_amount,})

pet_store/cart/templates/cart/cart_home.html
{% include 'base/header.html' %}
    {% block content %}
        <form action="{% url 'orders:place_order' %}">
        <table class="table table-striped">
            <thead>
                <th scope="col">Pet Name</th>
                <th scope="col">Quantity</th>
                <th scope="col">Price</th>
                <th scope="col">Total Price</th>
                <th scope="col">Action</th>
            </thead>

            {% if flag %}
                <tbody>
                    {% for item in items %}
                        <tr>
                            <td><img src="{{ item.pet.image.url }}" width="100px" height="100px">
                                <br/>
                                <h4>{{ item.pet.name }}</h4>
                            </td>

                            <td>
                                <input type="number" name="qnt" min="0" value="{{ item.quantity }}" id="quantity{{item.id}}">
                            </td>
                                                        
                            <td>
                                {{ item.pet.price }}
                            </td>

                            <td>
                                <input type="text" name="price" value="{{ item.totalprice }}" readonly
                                id="totalprice{{ item.id }}">

                            </td>

                            <td>
                               <a href="{% url 'cart_delete' item.id %}" class="btn btn-danger" data-id="{{ item.id }}">Delete</a>
                            </td>

                         </tr>
                         
                         {% endfor %}

                </tbody>
            {% else %}
                <h4>No Products Added in Cart........</h4>
            {% endif %}    
        </table>

        <h4>Total Amount:<span id="totalamount">{{ totalamount }}</span></h4>

        <button type="submit">Proceed to Pay</button>
    </form>
        <script>

            $(document).ready(function(){
            //  $('input[name= "qnt"]').change(function(){
                $('form').submit(function(e){
                    e.preventDefault();
                    var totalamount = parseFloat($("#totalamount").text()).toFixed(2);
                    window.location.href= $(this).attr('action')+ '?totalamount=' + totalamount;


                });    
                    localStorage.clear() // Local cache Remove your Data

                    // Set quantity to 1 and update total price when reloaded

                    $('input[name="qnt"]').each(function(){
                        var id = $(this).closest('tr').find('a').data('id');
                        // console.log(id);
                        var price = $(this).closest('tr').find('td:nth-child(3)').text();
                        
                        var totalprice = parseFloat(price)*1;
                        
                        $(this).val(1);
                    });

                    // Calculate and Update total amount
                    

                    function CalculateTotalAmount(){
                        var totalamount = 0;
                        $('input[name = "qnt"]').each(function(){
                            var id = $(this).closest('tr').find('a').data('id');
                            // console.log(id);
                            var quantity = $(this).val();
                            // alert(quantity);
                            var price = $(this).closest('tr').find('td:nth-child(3)').text();
                            // alert(price);
                            var totalprice = parseFloat(price)*quantity;
                            // alert(totalprice);s
                            $("#totalprice"+id).val(totalprice.toFixed(2));
                            totalamount += totalprice; // totalamount = totalamount + totalprice
                        });

                        $("#totalamount").text(totalamount.toFixed(2));
                    }
                
                

                    // Updating Quantity and Total Price
                    
                    $('input[name= "qnt"]').change(function(){
                        var quantity = $(this).val();
                        var price = $(this).closest('tr').find('td:nth-child(3)').text();
                        var id = $(this).closest('tr').find('a').data('id');

                        $.ajax({
                            url: '/cart/updatecart/' + id + '/',
                            method: 'POST',
                            data: {'qnt':quantity ,'price':price ,'id':id ,'csrfmiddlewaretoken':'{{ csrf_token}}'},
                            success: function(response){
                                $("#totalprice"+id).val(response.totalprice);
                                CalculateTotalAmount();
                                var totalamount = $("#totalamount").text();
                                sessionStorage.setItem('totalamount',totalamount); // to see sessaion value
                            },
                            error:function(){
                                alert("Error updating cart");
                            }
                        });
                    });


                    //calculate and update the initial amount.
                    CalculateTotalAmount();
                
                });
            

        </script>




    {% endblock %}                
{% include 'base/footer.html' %}